name: Release

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_LOWER: ${{ github.repository | toLower }}


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train (full)
        run: python train.py

      - name: Build image
        run: |
          echo "${GITHUB_REF_NAME}" > VERSION
          docker build -t $REGISTRY/${IMAGE_NAME_LOWER}:${GITHUB_REF_NAME} .

      - name: Smoke container
        run: |
          docker run -d -p 8000:8000 --name svc $REGISTRY/${IMAGE_NAME_LOWER}:${GITHUB_REF_NAME}
          sleep 2
          curl -f http://localhost:8000/health

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push $REGISTRY/${IMAGE_NAME_LOWER}:${GITHUB_REF_NAME}

      - name: Read metrics
        id: metrics
        run: echo "json=$(cat models/metrics_${GITHUB_REF_NAME}.json)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            See CHANGELOG.md for details.
            Metrics:
            ```
            ${{ steps.metrics.outputs.json }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
